iec60730b: zep: Fix compilation error for Cortex M33 platforms
Fixes compilation error for Cortex M33 platforms.
There was the naming conflict for "RO" definition in
in zephyr/include/zephyr/arch/arm/mpu/arm_mpu_v8.h:64:25
and source/iec60730b_types.h: fs_aio_a8_t->RO

Signed-off-by: Andrej Butok <andrey.butok@nxp.com>